name: farmer_app
version: 1.0.0+1
publish_to: none
description: farmer_app clg
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  google_fonts: ^2.0.0
  velocity_x: ^3.0.0
  flutter_spinkit: ^5.0.0
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  get: 4.1.4
  image_picker: 0.8.4+2
  firebase_storage: 10.0.5
  path: 1.8.0
  cached_network_image: 3.1.0
  location: 4.3.0
  weather: 2.0.1
  flutter: 
    sdk: flutter
  custom_utils: 
    git: https://github.com/imsmilegarg/custom_utils.git

dev_dependencies: 
  flutter_native_splash: ^1.1.8+4
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#118352'
  image: assets/splash.png

flutter: 
  assets: 
    - assets/
    - assets/promo/
    - assets/Misc/
  uses-material-design: true

